package microservices.backend.eir_catalog_core_backend.enums;

public enum AccountAddonBundle {
	MDMSSF,
	MDMSSFACC,
	MISCACCCHARGEACCESSORY,
	MISCACCCHARGEDEVICE,
	MISCACCCHARGEOTHER,
	MISCACCCHARGEREPAIR,
	MISCCHARGEACCESSORY,
	MISCCHARGEDEVICE,
	MISCCHARGEOTHER,
	MISCCHARGEREPAIR,
	SHDDATA,
	SHDDATA1TB,
	SHDDATA2TB,
	SHDDATA3TB,
	SHDDATA600GB,
	SHDINTVOICE,
	SHDVOICEAOW1000,
	SHDVOICEAOW2000,
	SHDVOICEAOW4000,
	BULKSMS1K,
	BULKSMS5K,
	BULKSMS20K,
	BULKSMS100K,
	BULKSMS250K,
	BULKSMS1M
}
