package microservices.backend.eir_subscription_management_backend.enums;

public enum TerminationReason {
	BILLED_WITHOUT_SERVICE,
	BILLING_ISSUE,
	COMPETITOR_OFFER,
	COVERAGE_ISSUES,
	DECEASED_CUSTOMER,
	HIGH_BILL_DUE_TO_OUT_OF_BUNDLE_CHARGES,
	NOT_USING_THE_SERVICE,
	POOR_CUSTOMER_SERVICE,
	PORTING_ISSUE,
	SIM_DOES_NOT_WORK_IN_THE_HANDSET,
	SIM_ISSUES,
	SIM_NOT_DELIVERED,
	UNHAPPY_WITH_CHARGES_ON_THE_BILL,
	COLLECTION,
	OTHER
}
