package microservices.backend.eir_order_management_backend.enums;

public enum EventType {
	CREATE_PRODUCT_ORDER,
	SERVICE_FULFILLMENT_TERMINATE_SERVICE,
	REPLACE_PRODUCT_ORDER,
	SERVICE_FULFILLMENT_SWAP_MSISDN,
	SERVICE_FULFILLMENT_SWAP_SIM,
	SERVICE_FULFILLMENT_REACTIVATE_SERVICE,
	SERVICE_FULFILLMENT_ADD_ITEM,
	SERVICE_FULFILLMENT_REMOVE_ITEM,
	CUSTOMER_REGISTRATION_ORDER,
	CREATE_ACCOUNT_ORDER,
	CREATE_SUBSCRIBER_ORDER,
	CREATE_HARDWARE_FUND_ORDER,
	ACTIVATE_SUBSCRIBER_ORDER,
	RENEW_HARDWARE_FUND_ORDER,
	CHANGE_OFFER_ORDER,
	CREATE_EQUIPMENT_ORDER,
	ADD_ACCOUNT_ADDON_ORDER,
	REMOVE_ACCOUNT_ADDON_ORDER
}
