package microservices.frontend.tecrep_monitor.enums;

public enum InventoryPool {
	METEOR_PAIRED_CUSTOMER_POOL,
	METEOR_UNPAIRED_POOL,
	TEST_PAIRED_POOL,
	METEORITE_POOL,
	EIRCOM_PAIRED_CUSTOMER_POOL,
	EIRCOM_UNPAIRED_POOL,
	TEST_UNPAIRED_POOL,
	ION_PAIRED_POOL,
	ION_UNPAIRED_POOL
}
