package microservices.backend.keycloak.enums;

public enum Microservice {
	ACQUISITIONS_UI,
	ACCOUNTS_RECEIVABLE,
	CONTACT_MANAGEMENT,
	CUSTOMER_OFFER,
	ORDER_MANAGEMENT,
	PROSPECT,
	DOCUMENT,
	SUBSCRIPTION_MANAGEMENT,
	ADJUSTMENT,
	BARRING,
	BULK,
	MYGOMO,
	CATALOG_CORE,
	CDR_REPOSITORY,
	INVENTORY_MANAGEMENT,
	MNP,
	PROVISIONING_FACADE,
	B2B_CRM_UI,
	PAYG_CRM_UI,
	TECREP_MONITOR,
	EIR_CSR_UI
}
